name: backlinks-creation

on: push

jobs:
  backlinks:
    runs-on: ubuntu-latest
    steps:
     - name: copy files to .backlink folder
       uses: guilhermeprokisch/ideias_action@v0.1.2
       env:
         GH_PAT: ${{ secrets.GH_PAT }}
         ACTION_MAIL: guilherme.prokisch@gmail.com
         ACTION_NAME: guilhermeprokisch
         OWNER: guilhermeprokisch
         REPO_NAME: ideias
